name: Continuous Integration
on: [push]                      # Will make the workflow run every time you push to any branch

jobs:
  build:
    name: Build and test the application
    runs-on: ubuntu-latest      # Sets the build environment a machine with the latest Ubuntu installed
    steps:
    - uses: actions/checkout@v2 # Adds a step to checkout the repository code

    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.403' # SDK Version to use; x will use the latest version of the 3.1 channel

    - name: Run dotnet build 
      run: dotnet build

    - name: Run dotnet test
      run: dotnet test

    - uses: actions/setup-node@v1
      with:
        node-version: '14'

    - name: Run npm install
      run: npm install
      working-directory: DotnetTemplate.Web

    - name: Run npm run build
      run: npm run build
      working-directory: DotnetTemplate.Web

    - name: Run npm run lint
      run: npm run lint
      working-directory: DotnetTemplate.Web

    - name: Run npm t
      run: npm t
      working-directory: DotnetTemplate.Web
   
  deploy:
    name: Deploy the application
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
    - uses: actions/checkout@v2 # Adds a step to checkout the repository code

    - name: Get commit hash
      run: echo "COMMIT_HASH=${GITHUB_SHA::8}" >> $GITHUB_ENV

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Docker Login
      uses: docker/login-action@v1
      with:
        username: pcoulso1
        password: ${{ secrets.DOCKER_PASSWORD }}
  
    - name: Push to Docker Hub
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
            pcoulso1/dotnettemplate:latest
            pcoulso1/dotnettemplate:${{ env.COMMIT_HASH }}
            
    - uses: akhileshns/heroku-deploy@v3.6.8 # This is the action
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: dotnet-template-web
        heroku_email: pcoulson@btinternet.com
        usedocker: true          
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            